Repository TeJinSa/TeJinSa-Web-Project, pull requests merged in 2023-01, with the labels that each got.

#4 header component 디자인작업 및 기타 초기설정
  frontend/.eslintrc.json
  frontend/.gitignore
  frontend/.prettierrc
  frontend/package-lock.json
  frontend/package.json
  frontend/public/index.html
  frontend/src/App.tsx
  frontend/src/assets/header.png
  frontend/src/components/BasicLayout.tsx
  frontend/src/components/Header/constants.ts
  frontend/src/components/Header/index.tsx
  frontend/src/components/Header/login.tsx
  frontend/src/components/Header/notice.tsx
  frontend/src/global/global.style.ts
  frontend/src/index.tsx
  frontend/src/mocks/handlers/ranking.ts
  frontend/src/pages/Main.tsx
  frontend/src/pages/UserHome.tsx
  frontend/src/router/Router.tsx
  frontend/src/setupTests.ts
  frontend/tsconfig.json
Labels: 🎨 style, 🚪 init

#11 [FEAT] 로그인 기능 구현
  backend/.eslintrc.json
  backend/.prettierrc
  backend/ormconfig.ts
  backend/package-lock.json
  backend/package.json
  backend/src/app.ts
  backend/src/controllers/user.controllers.ts
  backend/src/entities/user.entity.ts
  backend/src/error/httpException.ts
  backend/src/models/user.model.ts
  backend/src/routes/user.ts
  backend/src/services/user.service.ts
  backend/tsconfig.json
Labels: ⚙️ feat

#12 [FEAT] 로그아웃
  backend/src/controllers/user.controllers.ts
  backend/src/routes/user.ts
Labels: ⚙️ feat, BE

#8 [FEAT] UserInfoContainer 구현
  frontend/.eslintrc.json
  frontend/.prettierrc
  frontend/src/App.tsx
  frontend/src/components/BasicLayout.tsx
  frontend/src/components/UserInfoContainer/index.tsx
  frontend/src/global/global.style.ts
  frontend/src/mocks/handlers/index.ts
  frontend/src/mocks/handlers/userProfile.ts
  frontend/src/pages/UserHome.tsx
Labels: ⚙️ feat

#19 [FEAT] 푼 문제 목록 관련 기능
  frontend/src/components/ProblemControlDropdown/index.tsx
  frontend/src/components/ProblemList/index.tsx
  frontend/src/components/ProblemListItem/index.tsx
  frontend/src/components/UserCommonContainer/index.tsx
  frontend/src/mocks/handlers/index.ts
  frontend/src/mocks/handlers/solvedProblem.ts
  frontend/src/pages/UserHome.tsx
  frontend/src/types/solvedProblem.d.ts
Labels: ⚙️ feat

#10 login 기능 추가
  frontend/.eslintrc.json
  frontend/src/api/login.ts
  frontend/src/components/Header/index.tsx
  frontend/src/components/Header/login.tsx
  frontend/src/mocks/handlers/index.ts
  frontend/src/mocks/handlers/login.ts
  frontend/src/utils/constants/url.ts
Labels: ⚙️ feat

#13 [INIT] styled-components -> tailwind-css 전환
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/Header/index.tsx
  frontend/src/components/Header/login.tsx
  frontend/src/components/Header/notice.tsx
  frontend/src/global/global.style.ts
  frontend/src/index.css
  frontend/src/index.tsx
  frontend/src/mocks/handlers/index.ts
  frontend/tailwind.config.js
Labels: 🎨 style

#22 [FEAT] 푼 문제 생성, 목록, 삭제
  backend/ormconfig.ts
  backend/package-lock.json
  backend/package.json
  backend/src/app.ts
  backend/src/controllers/problem.controllers.ts
  backend/src/entities/platformLevel.entity.ts
  backend/src/entities/problem.entity.ts
  backend/src/entities/user.entity.ts
  backend/src/middlewares/auth.ts
  backend/src/middlewares/validateBody.ts
  backend/src/models/problem.model.ts
  backend/src/models/user.model.ts
  backend/src/routes/problem.ts
  backend/src/seeds/platformLevel.seeder.ts
  backend/src/services/problem.service.ts
  backend/src/services/user.service.ts
Labels: ⚙️ feat, BE

#25 [FEAT] main 및 user페이지 이동 위한 redirect 기능 추가
  frontend/src/components/Header/index.tsx
  frontend/src/components/Header/login.tsx
Labels: ⚙️ feat

#26 user 상태관리를 위해 context api를 활용
  frontend/src/App.tsx
  frontend/src/components/Header/login.tsx
  frontend/src/contexts/index.tsx
  frontend/src/contexts/user.tsx
  frontend/src/mocks/handlers/login.ts
  frontend/src/types/userInterface.ts
Labels: 🚪 init, 🪛 refactor

#27 main page의 common tap container
  frontend/src/components/BasicLayout.tsx
  frontend/src/components/CommonTapContainer/index.tsx
  frontend/src/components/Header/index.tsx
  frontend/src/pages/Main.tsx
  frontend/tailwind.config.js
Labels: ⚙️ feat, 🎨 style
